/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-09-28 08:03:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import supportClasses.DatabaseInteraction;
import supportClasses.QueryResult;

public final class launch_005fsimulation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	// get post variables NEED uncommenten
	String simulationName = request.getParameter("simulationName");
	String simulationDescription = request.getParameter("description");
	String strategyId = request.getParameter("strategyId");
	String userId = request.getSession().getAttribute("loggedInUserId").toString();
	String startDate = request.getSession().getAttribute("startDate").toString();
	String endDate = request.getSession().getAttribute("endDate").toString();
	
	DatabaseInteraction dbInt = new DatabaseInteraction("backtest_real","webapp");
	dbInt.addSimulation(simulationName, simulationDescription, userId, strategyId);
	
	// TODO kan voor race condition zorgen als naam van sim veranderd is ondertussen
	QueryResult queryResult = dbInt.executeQuery(String.format("SELECT id FROM simulation WHERE name='%s'",simulationName));
	String simulationId = queryResult.iterator().next().get("id").toString();
	
	// methodName en args halen uit strategy record uit database
	queryResult = dbInt.executeQuery(String.format("SELECT method, parameters FROM strategy WHERE id='%s'",strategyId));
	String methodId = queryResult.iterator().next().get("method").toString();
	String methodArguments = queryResult.iterator().next().get("parameters").toString();
	queryResult = dbInt.executeQuery(String.format("SELECT name FROM strategy WHERE id='%s'",methodId));
	String methodName = queryResult.iterator().next().get("name").toString();
	
	// bash process launcher
	// NEED url aanpassen
	ProcessBuilder b = new ProcessBuilder("/bin/bash","/home/nero/GIT/Bitbucket/pythonBeurs/WebSlaves/launch_new_task",methodName,methodArguments,simulationId,startDate,endDate);
	b.start();
	
	out.write("simulation started");

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
